name: Push to AWS CodeCommit

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push main branch to CodeCommit
        env:
          AWS_USERNAME: ${{ secrets.AWS_USERNAME }}
          AWS_PASSWORD: ${{ secrets.AWS_PASSWORD }}
        run: |
          git remote add aws https://${AWS_USERNAME}:${AWS_PASSWORD}@git-codecommit.ap-southeast-2.amazonaws.com/v1/repos/raghureplsce
          git push aws main
